### ISSUE TITLE
Auto updating installed apps

### ISSUE THREAD

**Issue by gerroon** [ligi/FAST#63]
Hi

This is a a great launcher but one if that I am having is that it does not  update the app cache after installing a new app via Fdroid. I end up recachign manually which messes up the last opened/frequent apps (I use last opened order)

**Comment by ligi** [comment]
this bug is fixed in the latest beta ( 6.0 ) and I hope to roll it out to public soon - thanks for reporting!

**Comment by gerroon** [comment]
Hi

This bug still rocking I think. It has an issue with updating apps from Fdroid and OanBackups installed apps. They never show up unless I clear the cache. But that destrosy the app sorting :(

thanks
